// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS.Logging.API.Database;

#nullable disable

namespace RS.Logging.API.Database.Migrations
{
    [DbContext(typeof(LogsDbContext))]
    [Migration("20220214134700_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RS.Logging.API.Domain.Log", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("IdProcess")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("LogLevel")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id", "IdProcess");

                    b.HasIndex(new[] { "DateCreated" }, "idx_Logs_DateCreated");

                    b.HasIndex(new[] { "DateCreated", "IdProcess" }, "idx_Logs_DateCreated-IdProcess");

                    b.HasIndex(new[] { "DateCreated", "LogLevel" }, "idx_Logs_DateCreated-LogLevel");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
