// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS.Log.API.Database;

namespace RS.Log.API.Database.Migrations
{
    [DbContext(typeof(LogsContext))]
    [Migration("20211109175814_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RS.Log.Domain.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DateCreated" }, "idx_Logs_DateCreated");

                    b.HasIndex(new[] { "DateCreated", "Message" }, "idx_Logs_DateCreated-Message");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
