// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS.Logstream.Infra.Contexts;

#nullable disable

namespace RS.Logstream.Infra.Migrations.SqlServer
{
    [DbContext(typeof(RSLogstreamDbContext))]
    [Migration("20260629013905_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RS.Logstream.Domain.ApiCall.ApiCallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id_ApiCallLog")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_CorrelationId")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("nr_DurationMs")
                        .HasColumnOrder(6);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ds_ErrorMessage")
                        .HasColumnOrder(11);

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_HttpMethod")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit")
                        .HasColumnName("fl_IsSuccess")
                        .HasColumnOrder(3);

                    b.Property<string>("RequestBody")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ds_RequestBody")
                        .HasColumnOrder(8);

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ds_RequestHeaders")
                        .HasColumnOrder(9);

                    b.Property<string>("ResponseBody")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ds_ResponseBody")
                        .HasColumnOrder(10);

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("nr_ResponseStatusCode")
                        .HasColumnOrder(5);

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_TenantId")
                        .HasColumnOrder(12);

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_TraceId")
                        .HasColumnOrder(14);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ds_Url")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationId" }, "idx_TB_ApiCallLog_ds_CorrelationId");

                    b.HasIndex(new[] { "TenantId" }, "idx_TB_ApiCallLog_ds_TenantId");

                    b.HasIndex(new[] { "TraceId" }, "idx_TB_ApiCallLog_ds_TraceId");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_TB_ApiCallLog_dt_CreatedAt");

                    b.HasIndex(new[] { "IsSuccess" }, "idx_TB_ApiCallLog_fl_IsSuccess");

                    b.HasIndex(new[] { "ResponseStatusCode" }, "idx_TB_ApiCallLog_nr_ResponseStatusCode");

                    b.ToTable("TB_ApiCallLog", (string)null);
                });

            modelBuilder.Entity("RS.Logstream.Domain.Log.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id_Log")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_CorrelationId")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<short>("LogLevel")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("ie_LogLevel")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_Message")
                        .HasColumnOrder(4);

                    b.Property<string>("StackTrace")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ds_StackTrace")
                        .HasColumnOrder(5);

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_TenantId")
                        .HasColumnOrder(6);

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_TraceId")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationId" }, "idx_TB_Log_ds_CorrelationId");

                    b.HasIndex(new[] { "TenantId" }, "idx_TB_Log_ds_TenantId");

                    b.HasIndex(new[] { "TraceId" }, "idx_TB_Log_ds_TraceId");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_TB_Log_dt_CreatedAt");

                    b.HasIndex(new[] { "CreatedAt", "LogLevel" }, "idx_TB_Log_dt_CreatedAt-ie_LogLevel");

                    b.ToTable("TB_Log", (string)null);
                });

            modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id_LogProcess")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_CorrelationId")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("nm_Process")
                        .HasColumnOrder(4);

                    b.Property<int>("ProcessId")
                        .HasColumnType("INT")
                        .HasColumnName("id_Process")
                        .HasColumnOrder(2);

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_TenantId")
                        .HasColumnOrder(5);

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_TraceId")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationId" }, "IDX-TB_LogProcess_ds_CorrelationId");

                    b.HasIndex(new[] { "TenantId" }, "IDX-TB_LogProcess_ds_TenantId");

                    b.HasIndex(new[] { "TraceId" }, "IDX-TB_LogProcess_ds_TraceId");

                    b.HasIndex(new[] { "CreatedAt" }, "IDX-TB_LogProcess_dt_CreatedAt");

                    b.HasIndex(new[] { "CreatedAt", "ProcessId" }, "IDX-TB_LogProcess_dt_CreatedAt-id_Process");

                    b.ToTable("TB_LogProcess", (string)null);
                });

            modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcessDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id_LogProcessDetails")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_CorrelationId")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<short>("LogLevel")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("ie_LogLevel")
                        .HasColumnOrder(3);

                    b.Property<long>("LogProcessId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("cd_Process")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_Message")
                        .HasColumnOrder(5);

                    b.Property<string>("StackTrace")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ds_StackTrace")
                        .HasColumnOrder(6);

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ds_TraceId")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("LogProcessId");

                    b.HasIndex(new[] { "CorrelationId" }, "idx-TB_LogProcessDetail_ds_CorrelationId");

                    b.HasIndex(new[] { "TraceId" }, "idx-TB_LogProcessDetail_ds_TraceId");

                    b.HasIndex(new[] { "CreatedAt", "LogProcessId" }, "idx-TB_LogProcessDetail_dt_CreatedAt-cd_Process");

                    b.HasIndex(new[] { "CreatedAt" }, "idx-TB_LogProcess_dt_CreatedAt");

                    b.ToTable("TB_LogProcessDetail", (string)null);
                });

            modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcessDetail", b =>
                {
                    b.HasOne("RS.Logstream.Domain.LogProcess.LogProcess", "LogProcess")
                        .WithMany("LorProcessDetailList")
                        .HasForeignKey("LogProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK-TB_LogProcessDetail_cd_Process-TB_LogProcess_id_LogProcess");

                    b.Navigation("LogProcess");
                });

            modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcess", b =>
                {
                    b.Navigation("LorProcessDetailList");
                });
#pragma warning restore 612, 618
        }
    }
}
