// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS.Logging.Infra.Contexts;

#nullable disable

namespace RS.Logging.Infra.Migrations
{
    [DbContext(typeof(RSLoggingDbContext))]
    [Migration("20230930224026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RS.Logging.Domain.Log.Log", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id_Log")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("LogLevel")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("ie_LogLevel")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("ds_Message")
                        .HasColumnOrder(4);

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext")
                        .HasColumnName("ds_StackTrace")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_Logs_CreatedAt");

                    b.HasIndex(new[] { "CreatedAt", "LogLevel" }, "idx_Logs_CreatedAt-LogLevel");

                    b.ToTable("TB_Log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
