// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS.Logging.Infra.Contexts;

#nullable disable

namespace RS.Logging.Infra.Migrations
{
    [DbContext(typeof(RSLoggingDbContext))]
    [Migration("20231028132620_LogProcess")]
    partial class LogProcess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RS.Logging.Domain.Log.Log", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("id_Log")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("NOW()");

                    b.Property<ushort>("LogLevel")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("ie_LogLevel")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("ds_Message")
                        .HasColumnOrder(4);

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext")
                        .HasColumnName("ds_StackTrace")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_TB_Log_dt_CreatedAt");

                    b.HasIndex(new[] { "CreatedAt", "LogLevel" }, "idx_TB_Log_dt_CreatedAt-ie_LogLevel");

                    b.ToTable("TB_Log", (string)null);
                });

            modelBuilder.Entity("RS.Logging.Domain.LogProcess.LogProcess", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("id_LogProcess")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("nm_Process")
                        .HasColumnOrder(4);

                    b.Property<uint>("ProcessId")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("id_Process")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx-TB_LogProcess_dt_CreatedAt");

                    b.HasIndex(new[] { "CreatedAt", "ProcessId" }, "idx-TB_LogProcess_dt_CreatedAt-id_Process");

                    b.ToTable("TB_LogProcess", (string)null);
                });

            modelBuilder.Entity("RS.Logging.Domain.LogProcess.LogProcessDetails", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("id_LogProcessDetails")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_CreatedAt")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("NOW()");

                    b.Property<ushort>("LogLevel")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("ie_LogLevel")
                        .HasColumnOrder(3);

                    b.Property<ulong>("LogProcessId")
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("cd_Process")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("ds_Message")
                        .HasColumnOrder(5);

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext")
                        .HasColumnName("ds_StackTrace")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("LogProcessId");

                    b.HasIndex(new[] { "CreatedAt", "LogProcessId" }, "idx-TB_LogProcessDetail_dt_CreatedAt-cd_Process");

                    b.HasIndex(new[] { "CreatedAt" }, "idx-TB_LogProcess_dt_CreatedAt")
                        .HasDatabaseName("idx-TB_LogProcess_dt_CreatedAt1");

                    b.ToTable("TB_LogProcessDetail", (string)null);
                });

            modelBuilder.Entity("RS.Logging.Domain.LogProcess.LogProcessDetails", b =>
                {
                    b.HasOne("RS.Logging.Domain.LogProcess.LogProcess", "LogProcess")
                        .WithMany("LorProcessDetailList")
                        .HasForeignKey("LogProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogProcess");
                });

            modelBuilder.Entity("RS.Logging.Domain.LogProcess.LogProcess", b =>
                {
                    b.Navigation("LorProcessDetailList");
                });
#pragma warning restore 612, 618
        }
    }
}
