// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS.Logstream.Infra.Contexts;

#nullable disable

namespace RS.Logstream.Infra.Migrations.MariaDB
{
	[DbContext(typeof(RSLoggingDbContext))]
	[Migration("20260614125641_AddTenantCorrelationTraceFullText")]
	partial class AddTenantCorrelationTraceFullText
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.UseCollation("utf8_general_ci")
				.HasAnnotation("ProductVersion", "9.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 64);

			MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

			modelBuilder.Entity("RS.Logstream.Domain.Log.Log", b =>
				{
					b.Property<ulong>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("BIGINT UNSIGNED")
						.HasColumnName("id_Log")
						.HasColumnOrder(1);

					MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

					b.Property<string>("CorrelationId")
						.HasMaxLength(64)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_CorrelationId")
						.HasColumnOrder(7);

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnType("datetime(6)")
						.HasColumnName("dt_CreatedAt")
						.HasColumnOrder(3)
						.HasDefaultValueSql("NOW()");

					b.Property<ushort>("LogLevel")
						.HasColumnType("SMALLINT UNSIGNED")
						.HasColumnName("ie_LogLevel")
						.HasColumnOrder(2);

					b.Property<string>("Message")
						.IsRequired()
						.HasMaxLength(255)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_Message")
						.HasColumnOrder(4);

					b.Property<string>("StackTrace")
						.HasColumnType("LONGTEXT")
						.HasColumnName("ds_StackTrace")
						.HasColumnOrder(5);

					b.Property<string>("TenantId")
						.HasMaxLength(100)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_TenantId")
						.HasColumnOrder(6);

					b.Property<string>("TraceId")
						.HasMaxLength(64)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_TraceId")
						.HasColumnOrder(8);

					b.HasKey("Id");

					b.HasIndex(new[] { "Message" }, "ft_TB_Log_ds_Message")
						.HasAnnotation("MySql:FullTextIndex", true);

					b.HasIndex(new[] { "StackTrace" }, "ft_TB_Log_ds_StackTrace")
						.HasAnnotation("MySql:FullTextIndex", true);

					b.HasIndex(new[] { "CorrelationId" }, "idx_TB_Log_ds_CorrelationId");

					b.HasIndex(new[] { "TenantId" }, "idx_TB_Log_ds_TenantId");

					b.HasIndex(new[] { "TraceId" }, "idx_TB_Log_ds_TraceId");

					b.HasIndex(new[] { "CreatedAt" }, "idx_TB_Log_dt_CreatedAt");

					b.HasIndex(new[] { "CreatedAt", "LogLevel" }, "idx_TB_Log_dt_CreatedAt-ie_LogLevel");

					b.ToTable("TB_Log", (string)null);
				});

			modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcess", b =>
				{
					b.Property<ulong>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("BIGINT UNSIGNED")
						.HasColumnName("id_LogProcess")
						.HasColumnOrder(1);

					MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

					b.Property<string>("CorrelationId")
						.HasMaxLength(64)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_CorrelationId")
						.HasColumnOrder(6);

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnType("datetime(6)")
						.HasColumnName("dt_CreatedAt")
						.HasColumnOrder(3)
						.HasDefaultValueSql("NOW()");

					b.Property<string>("Name")
						.HasMaxLength(255)
						.HasColumnType("VARCHAR")
						.HasColumnName("nm_Process")
						.HasColumnOrder(4);

					b.Property<uint>("ProcessId")
						.HasColumnType("INT UNSIGNED")
						.HasColumnName("id_Process")
						.HasColumnOrder(2);

					b.Property<string>("TenantId")
						.HasMaxLength(100)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_TenantId")
						.HasColumnOrder(5);

					b.Property<string>("TraceId")
						.HasMaxLength(64)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_TraceId")
						.HasColumnOrder(7);

					b.HasKey("Id");

					b.HasIndex(new[] { "CorrelationId" }, "IDX-TB_LogProcess_ds_CorrelationId");

					b.HasIndex(new[] { "TenantId" }, "IDX-TB_LogProcess_ds_TenantId");

					b.HasIndex(new[] { "TraceId" }, "IDX-TB_LogProcess_ds_TraceId");

					b.HasIndex(new[] { "CreatedAt" }, "IDX-TB_LogProcess_dt_CreatedAt");

					b.HasIndex(new[] { "CreatedAt", "ProcessId" }, "IDX-TB_LogProcess_dt_CreatedAt-id_Process");

					b.ToTable("TB_LogProcess", (string)null);
				});

			modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcessDetail", b =>
				{
					b.Property<ulong>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("BIGINT UNSIGNED")
						.HasColumnName("id_LogProcessDetails")
						.HasColumnOrder(1);

					MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

					b.Property<string>("CorrelationId")
						.HasMaxLength(64)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_CorrelationId")
						.HasColumnOrder(7);

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnType("datetime(6)")
						.HasColumnName("dt_CreatedAt")
						.HasColumnOrder(4)
						.HasDefaultValueSql("NOW()");

					b.Property<ushort>("LogLevel")
						.HasColumnType("SMALLINT UNSIGNED")
						.HasColumnName("ie_LogLevel")
						.HasColumnOrder(3);

					b.Property<ulong>("LogProcessId")
						.HasColumnType("BIGINT UNSIGNED")
						.HasColumnName("cd_Process")
						.HasColumnOrder(2);

					b.Property<string>("Message")
						.IsRequired()
						.HasMaxLength(255)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_Message")
						.HasColumnOrder(5);

					b.Property<string>("StackTrace")
						.HasColumnType("LONGTEXT")
						.HasColumnName("ds_StackTrace")
						.HasColumnOrder(6);

					b.Property<string>("TraceId")
						.HasMaxLength(64)
						.HasColumnType("VARCHAR")
						.HasColumnName("ds_TraceId")
						.HasColumnOrder(8);

					b.HasKey("Id");

					b.HasIndex("LogProcessId");

					b.HasIndex(new[] { "Message" }, "ft_TB_LogProcessDetail_ds_Message")
						.HasAnnotation("MySql:FullTextIndex", true);

					b.HasIndex(new[] { "StackTrace" }, "ft_TB_LogProcessDetail_ds_StackTrace")
						.HasAnnotation("MySql:FullTextIndex", true);

					b.HasIndex(new[] { "CorrelationId" }, "idx-TB_LogProcessDetail_ds_CorrelationId");

					b.HasIndex(new[] { "TraceId" }, "idx-TB_LogProcessDetail_ds_TraceId");

					b.HasIndex(new[] { "CreatedAt", "LogProcessId" }, "idx-TB_LogProcessDetail_dt_CreatedAt-cd_Process");

					b.HasIndex(new[] { "CreatedAt" }, "idx-TB_LogProcess_dt_CreatedAt");

					b.ToTable("TB_LogProcessDetail", (string)null);
				});

			modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcessDetail", b =>
				{
					b.HasOne("RS.Logstream.Domain.LogProcess.LogProcess", "LogProcess")
						.WithMany("LorProcessDetailList")
						.HasForeignKey("LogProcessId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired()
						.HasConstraintName("FK-TB_LogProcessDetail_cd_Process-TB_LogProcess_id_LogProcess");

					b.Navigation("LogProcess");
				});

			modelBuilder.Entity("RS.Logstream.Domain.LogProcess.LogProcess", b =>
				{
					b.Navigation("LorProcessDetailList");
				});
#pragma warning restore 612, 618
		}
	}
}
